- hosts: all
  become: yes
  tasks:

  - name: Create a network with custom IPv4 address config
    community.docker.docker_network:
      name: flaskapp_network
      driver: bridge
      attachable: true
      ipam_config:
        - subnet: 172.16.0.0/28
          gateway: 172.16.0.1
          iprange: 172.16.0.0/28

    - name: Create the MySQL db volume
    community.docker.docker_volume:
      name: db_vol
      driver: local

    - name: Create the data container
      community.docker.docker_container:
        name: mydata_container
        image: busybox
        volumes:
          - /db_vol

    - name: Deploy flask-app
      community.docker.docker_container:
        name: flask-app
        image: flask-app:latest
        ports:
          - "8000:8000"
        networks:
          - name: flaskapp_network
        volumes:
          - flask-app:/var/www/html
        env:
          DATABASE_HOST: "db"
          DATABASE_USER: "devops04"
          DATABASE_PASSWORD: "chukula@adho13"
          DATABASE_NAME: "ansible"
          
        restart_policy: always

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: flaskapp_network
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "exampledb"
          MYSQL_USER: "exampleuser"
          MYSQL_PASSWORD: "examplepass"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always