---
- name: Build and Run Flask App and MySQL Containers
  hosts: demoserver
  become: yes
  become_method: sudo

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: install docker-py package
      pip:
        name: docker-py
        state: present

    - name: Create Custom Bridge Network
      docker_network:
        name: flaskapp_network
        state: present
        attachable: true
        ipam_config:
          - subnet: 172.16.0.0/28
            gateway: 172.16.0.1
            iprange: 172.16.0.0/28

    - name: Create BusyBox Data Container
      docker_container:
        name: busybox-data-container
        image: busybox
        state: started
        volumes:
          - /data # Mount an empty volume to /data in the busybox container

    # - name: Build Flask App Docker Image
    #   docker_image:
    #     name: flask-app:1.0.0
    #     source: build
    #     build:
    #       path: ./Code
    #     state: present

    # - name: Run Flask App Container
    #   docker_container:
    #     name: flask-app-container
    #     image: flask-app:1.0.0
    #     state: started
    #     ports:
    #       - '5000:5000'
    #     volumes:
    #       - /data:/app/data
    #     networks:
    #       - flask_network

    - name: Build MySQL Docker Container
      docker_image:
        name: mysql-db:1.0.0
        source: build
        build:
          path: db
        state: present

    - name: Run MySQL Container
      docker_container:
        name: mysql-db-container
        image: mysql-db:1.0.0
        state: started
        env:
          MYSQL_ROOT_PASSWORD: '1'
          MYSQL_DATABASE: 'ansible'
          MYSQL_USER: 'devops04'
          MYSQL_PASSWORD: 'chukula@adho13'
        ports:
          - '3307:3306'
        volumes:
          - db:/var/lib/mysql
          - /data:/app/data
