---
- name: Build and Run Flask App and MySQL Containers
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: install docker-py package
      pip:
        name: docker-py
        state: present

    - name: Create Custom Bridge Network
      docker_network:
        name: flaskapp_network
        state: present
        attachable: true
        ipam_config:
          - subnet: 172.16.0.0/28
            gateway: 172.16.0.1
            iprange: 172.16.0.0/28

    - name: Create BusyBox Data Container
      docker_container:
        name: busybox-data-container
        image: busybox
        state: started
        tty: true
        volumes:
          - /data # Mount an empty volume to /data in the busybox container

    - name: Run Flask App Container
      docker_container:
        name: flask-app-container
        image: mrmiano/flaskapp:v1.0.0
        state: started
        ports:
          - '5000:5000'
        volumes:
          - /data:/app/data
        networks:
          - name: flaskapp_network

    - name: Run MySQL Container
      docker_container:
        name: mysql-db-container
        image: mrmiano/mysqldb_flask:v1.0.0
        state: started
        env:
          MYSQL_ROOT_PASSWORD: '1'
          MYSQL_DATABASE: 'ansible'
          MYSQL_USER: 'devops04'
          MYSQL_PASSWORD: 'chukula@adho13'
        ports:
          - '3307:3306'
        volumes:
          - db:/var/lib/mysql
          - /data:/app/data
        networks:
          - name: flaskapp_network
